num_motion: 9

motion0:
  pos: [0,0,-0.01]
  ori: [1,0,0,0]
  duration: 0.4
  b_relative: false

motion1:
  pos: [0.015, 0.015, 0.0]
  ori: [1,0,0,0]
  duration: 0.5
  b_relative: true

motion2:
  pos: [-0.03, -0.03, 0.0]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion3:
  pos: [0.01, 0.01, 0.01]
  ori: [1,0,0,0]
  duration: 0.5
  b_relative: true

motion4:
  pos: [0.0, 0.0, -0.02]
  ori: [1,0,0,0]
  duration: 0.5
  b_relative: true

motion5:
  pos: [0.015, 0.015, 0.005]
  ori: [1,0,0,0]
  duration: 0.5
  b_relative: true

motion6:
  pos: [-0.02, -0.02, 0.0]
  ori: [1,0,0,0]
  duration: 1.5
  b_relative: true

motion7:
  pos: [0.01, 0.01, 0.01]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true

motion8:
  pos: [0.0, 0.0, -0.02]
  ori: [1,0,0,0]
  duration: 1
  b_relative: true
